In [5]:
import pandas as pd
import numpy as np
import hashlib
from numpy import pi

In [49]:
transact = pd.DataFrame({'Node': [0,1,2,3,4], 'Transaction 1': [0,0,-3,3,0],
                          'Transaction 2': [2,0,-2,0,0]},dtype=object)
transact.set_index('Node',inplace=True)
transact.to_csv('Initial/transactions.csv')
transact.head()

     Transaction 1 Transaction 2
Node
0                0             2
1                0             0
2               -3            -2
3                3             0
4                0             0

In [4]:
path_transaction = 'Transactions/transactions.csv'
tran = pd.read_csv(path_transaction)
tran.set_index('Node', inplace=True)
tran.head()

      Transaction 1  Transaction 2
Node
1                 0              2
2                 0              0
3                -3             -2
4                 3              0
5                 0              0

In [5]:
block1 = pd.DataFrame({'Node': [1,2,3,4,5], 'Old Wallet': [20,20,20,20,20], 'Transaction 1': [0,0,-3,3,0],
                          'Transaction 2': [2,0,-2,0,0], 'Wallet': [22,20,15,23,20],
                   'Random number': ['01011','10110','11100','00000','10111'],
                   'prev_fidelity': [0,0.3,0.4,0.5,0.8]},dtype=object)
block1.set_index('Node',inplace=True)
block1.to_csv('Blocks/block1.csv')
block1.head()

     Old Wallet Transaction 1 Transaction 2 Wallet Random number prev_fidelity
Node
1            20             0             2     22         01011             0
2            20             0             0     20         10110           0.3
3            20            -3            -2     15         11100           0.4
4            20             3             0     23         00000           0.5
5            20             0             0     20         10111           0.8

In [6]:
path_block = 'Blocks/block1.csv'
df=pd.read_csv(path_block, dtype=object)
df.set_index('Node', inplace=True)
df.head()

     Old Wallet Transaction 1 Transaction 2 Wallet Random number prev_fidelity
Node
1            20             0             2     22         01011             0
2            20             0             0     20         10110           0.3
3            20            -3            -2     15         11100           0.4
4            20             3             0     23         00000           0.5
5            20             0             0     20         10111           0.8

In [7]:
n_nodes = 4
nodes = list(range(1,n_nodes+1))

block_num = 2   # number of new block  

path_old = 'Blocks/block' + str(block_num-1) + '.csv'
old_block = pd.read_csv(path_old)

old_block.head()

,Node,Old Wallet,Transaction 1,Transaction 2,Wallet,Random number,prev_fidelity
0,1,20,0,2,22,1011,0.0
1,2,20,0,0,20,10110,0.3
2,3,20,-3,-2,15,11100,0.4
3,4,20,3,0,23,0,0.5
4,5,20,0,0,20,10111,0.8

In [11]:
path_tran = 'Transactions/transactions.csv'
tran = pd.read_csv(path_tran)
tran.set_index('Node', inplace=True)


tran_1 = 'Transaction ' + str(2*(block_num-1)+1)
tran_2 = 'Transaction ' + str(2*block_num)


t_1 = [0,1,0,0,-1]
t_2 = [0,0,0,5,-5]

old_w = np.asarray(old_block['Wallet'].tolist())

# cambiar atributo de current block de la clase bloque? Definir el bloque con las transacciones iniciales
# y unos números iniciales
# funcion transaccion dentro de la clase bloque

node = 1

payment = 0.2*np.ones(5) 
payment[node-1]=1

new_w = list(old_w + np.asarray(t_1) + np.asarray(t_2) + payment)

new_block = pd.DataFrame({'Node': [1,2,3,4,5], 'Old Wallet': old_block['Wallet'], tran_1: list(t_1),
                          tran_2: list(t_2), 'New Wallet': new_w,
                   'Random number': ['01011','10110','11100','00000','10111'],
                   'prev_fidelity': [0,0.3,0.4,0.5,0.8]}, dtype=object)

new_block.set_index('Node',inplace=True)
new_block.to_csv('Blocks/block'+str(block_num)+'.csv')
new_block.head()

,Old Wallet,Transaction 3,Transaction 4,New Wallet,Random number,prev_fidelity
Node,,,,,,
1,22,0,0,23,01011,0
2,20,1,0,21.2,10110,0.3
3,15,0,0,15.2,11100,0.4
4,23,0,5,28.2,00000,0.5
5,20,-1,-5,14.2,10111,0.8

In [9]:
# Añadimos al csv de transacciones las nuevas transacciones
path_transaction = 'Transactions/transactions.csv'
tran = pd.read_csv(path_transaction)
tran.set_index('Node', inplace=True)
tran[tran_1]=t_1
tran[tran_2]=t_2
tran.to_csv('Transactions/transactions.csv')
tran.head()

      Transaction 1  Transaction 2  Transaction 3  Transaction 4
Node
1                 0              2              0              0
2                 0              0              1              0
3                -3             -2              0              0
4                 3              0              0              5
5                 0              0             -1             -5

In [ ]:
def transaction(t_number, node_1, wallet, sends, node_2):
    '''Write transaction information in a file.
    
    Input: 
    - node_1: number of sending node
    - wallet: money in node_1's wallet
    - sends: money node_1 sends to node_2
    - node_2: number of receiving node
    
    Output:
    - t_path: path of transaction file
    
    '''
    
    t_path = 'Transactions/transaction' + str(t_number) + '.txt'
    
    tran_1 = 'Transaction ' + str(2*(block_num-1)+1)
    tran_2 = 'Transaction ' + str(2*block_num)

    
    with open(t_path, 'w+') as t:
        t.write('Transaction number: ' + str(t_number) + '\n')
        t.write('Sending node: ' + str(node_1) + '\n')
        t.write('Wallet: ' + str(wallet) + '\n')
        t.write('Sends: ' + str(sends) + '\n')
        t.write('Receiving node: ' + str(sends))
    
    return t_path

## Block class

Each node starts with a copy of the blockchain, for this proof of concept we will use 5 nodes. In case we wanted to expand the blockchain, each new node should get a copy of the blockchain.

In [95]:
class node:
    
    def __init__(self, nodes, node_number, tran_block):
        '''Initialize block class. Initializes block number to 1, sets first block's path,
        number of nodes in the blockchain and transaction count.
        
        Input
        - block_path: path of the first block in the blockchain
        - tran_block: transactions per block
        '''
        
        self.nodes = list(range(nodes))
        self.node_number = node_number
        self.block_path = 'Node' + str(node_number) + '/Blocks/block1.csv'
        self.tran_path = 'Node' + str(node_number) + '/transactions.csv'
        self.tran_block = tran_block
        self.block_count = 1
        self.tran_count = 2
        
 
    def transaction(self, node_1, sends, node_2):
        
        prev_block = pd.read_csv(b.block_path)
        prev_block.set_index('Node', inplace=True)
        
        if prev_block.loc[node_1,'Wallet'] < sends:
            raise Exception('Error, not enough funds in wallet.')
        
        # Authorised transaction
        self.tran_count +=1
        
        list_tran = np.zeros(len(self.nodes))
        list_tran[node_1]= -sends
        list_tran[node_2] = sends
        
        df_tran = pd.read_csv(self.tran_path)
        df_tran.set_index('Node', inplace=True)
        
        tran_header = 'Transaction ' + str(self.tran_count)
        df_tran[tran_header] = list_tran
        df_tran.to_csv(self.tran_path)
    
    
    def get_payment(self, new_block):
        
        max_fidelity = new_block['prev_fidelity'].idxmax()
        payment = 0.2*np.ones(5) 
        payment[max_fidelity]=1
    
    def create_block(self, random_numbers, prev_fidelity):
        '''Write block information in a text file: block number, previous state and two transactions. 
        
        Input:
        - node_1: two nodes that send money
        - node_1: two nodes that receive money
        - sends: money the two nodes send
        - random_numbers: strings list
        - fidelity: list of float 
        '''
        
        prev_block = pd.read_csv(self.block_path)
        prev_block.set_index('Node', inplace=True)
        
        new_block = pd.DataFrame({'Node': self.nodes, 'Old Wallet': prev_block['Wallet'].tolist(),
                                  'Random number': random_numbers,
                               'prev_fidelity': prev_fidelity},dtype=object)
        new_block.set_index('Node', inplace=True)
        
        df_tran = pd.read_csv(self.tran_path)
        
        money_update=np.zeros(len(self.nodes))
        
        for i in range(self.tran_count-self.tran_block+1,self.tran_count+1):
            tran_header = 'Transaction ' + str(i)
            tran_i= df_tran[tran_header].tolist()
            new_block[tran_header] = tran_i
            money_update += np.asarray(tran_i)
        
        
        # Nodes get payment for solving previous block
        fid = new_block['prev_fidelity'].tolist()
        max_fidelity = fid.index(max(fid))
        payment = 0.2*np.ones(5) 
        payment[max_fidelity]=1
        
        old_wallet = np.asarray(new_block['Old Wallet'].tolist())
        new_block['Wallet'] = list(old_wallet + money_update + payment)

        # Update path and save block
        self.block_path = 'Node' + str(self.node_number) + '/Blocks/block' + str(self.block_count+1) + '.csv'
        new_block.to_csv(self.block_path)
        self.block_count += 1
                                
        
    def sha256(self,block_path):
        '''Create a hash from the block csv file.
        Input:
        - block_path: block path as a string
        '''
        
        with open(block_path, mode='rb') as block_file:
            content = block_file.read()
            sha256_hash = hashlib.sha256(content)
    
        return sha256_hash.hexdigest()
    
    def state_parameters(self):
        '''Create angles of the qubit from the block's hash.'''
        
        sha = self.sha256(self.block_path)
        θ = int(sha[0:32],16) % (2*pi)
        ϕ = int(sha[32:],16) % (2*pi)
        
        return θ, ϕ   
                                                
    
    def get_rand_numbers(self):
        
        return ['8934893','343482','32432','3442','42343']
    
                                
    def get_fidelity(self):
        '''Calculates the array with maximum fidelity.
        
        Returns:
        - Winner: node with maximum fidelity
        - Fidelity: array of fidelities obtained by the node who measured the highest fidelity
        '''
        
        winner = 0
        
        fidelity = [0.1,0,0.9,0.4,0.3]
        
        return 0, fidelity
        
        
        
    def update_blocks(self, winner): 
        winner_path = 'Nodes/Node' + str(winner) + '/Blocks/block' + str(self.block_count) + '.csv'
        
        for i in self.nodes:
            if i == winner:
                continue        
            loser_path = 'Nodes/Blocks/block' + str(i) + '.csv'
            #with open(winner_path, 'w+') as w:
                
                
                                
    def add_transactions(self, node_send, send, node_receive):  ############## TERMINAAAAR!!!!!!!
        '''Add transactions to the blockchain.
        
        Input:
        - node_send: list of nodes sending money
        - send: list of money sent (one corresponding to each node)
        - node_receive: list of nodes that receive the money
        '''
        
        for i in range(self.tran_block):    
            
            self.transaction(node_send[i], send[i], node_receive[i])
            
            if self.tran_count % self.tran_block == 0:
                
                rand = self.get_rand_numbers() # get random numbers for this round
                winner, prev_fidelity = self.get_fidelity() # previous fidelity
                self.create_block(rand, prev_fidelity)
                #self.update_blocks(winner) # update all nodes blocks

In [96]:
b=node(5,0,2)
b.transaction(1,10,3)

In [98]:
b.add_transactions([1,2], [1,3], [0,1])

In [82]:
prev_block = pd.read_csv(b.block_path)
prev_block.set_index('Node', inplace=True)
prev_block['prev_fidelity'].idxmax()

5